### ISSUE TITLE
Latest run of the scoreboard has 0% for all backends

### ISSUE THREAD

**Issue by garymm** [onnx/backend-scoreboard#38]
![image](https://user-images.githubusercontent.com/421339/172204666-b4f6ce7d-8c6f-457b-ac05-74e2e024a69a.png)

**Comment by garymm** [comment]
Might be fixed by ONNX 1.12 release. We'll wait to see.

**Comment by jcwchen** [comment]
It seems fixed after ONNX 1.12 release: http://onnx.ai/backend-scoreboard/. Still, the error should be more explicit, because I cannot find any clue about the exact failure in the CI.

**Comment by garymm** [comment]
Yay! I agree it should be improved, but closing this since the issue is resolved. We can open another issue to track improving logging if we need to.

**Comment by andife** [comment]
Maybe one should reopen it, because still or again everything has 0.00% or is it another error?

**Comment by jcwchen** [comment]
I guess it might fail due to `##[warning]The ubuntu-18.04 environment is deprecated, consider switching to ubuntu-20.04(ubuntu-latest), or ubuntu-22.04 instead. For more details see https://github.com/actions/virtual-environments/issues/6002`?

**Comment by jcwchen** [comment]
Sorry I might be wrong... The exact error should be: https://dev.azure.com/michalkarzynski/michalkarzynski/_build/results?buildId=4043&view=logs&j=0a95b365-dc93-5d9e-986d-67f66074ab02&t=f9fdf4fe-af39-5908-7d03-f8edf49c452f.
